package es.uva.eii.ds.empresa15.interfaz.paresVistaControl.empleado;

import es.uva.eii.ds.empresa15.negocio.controladoresCasoUso.ControladorCUIdentificarse;
import es.uva.eii.ds.empresa15.negocio.modelos.empleado.Empleado;
import es.uva.eii.ds.empresa15.negocio.modelos.empleado.rol.GerenteDeVentas;
import es.uva.eii.ds.empresa15.negocio.modelos.empleado.rol.PersonalAlmacen;
import es.uva.eii.ds.empresa15.negocio.modelos.empleado.rol.Rol;
import es.uva.eii.ds.empresa15.negocio.modelos.empleado.rol.TecnicoDelTaller;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 * Implementacion de VistaCUIdentificarse
 * 
 * @author mariher
 */
public class VistaCUIdentificarse extends javax.swing.JFrame {

    private final CtrlVistaCUIdentificarse controlador;
    private final ControladorCUIdentificarse controladorCU;
    
    /**
     * Creates new form VistaCUIdentificarse
     */
    public VistaCUIdentificarse() {
        initComponents();
        this.controladorCU = ControladorCUIdentificarse.getControlador();
        this.controlador = new CtrlVistaCUIdentificarse(this, this.controladorCU);
    }
    
    public VistaCUIdentificarse(Empleado e) {
        initComponents();
        this.controladorCU = ControladorCUIdentificarse.getControlador();
        this.controlador = new CtrlVistaCUIdentificarse(this, this.controladorCU);
        mostrarOpcionesRol(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        DNITextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        personalAlmacenPanel = new javax.swing.JPanel();
        almacenLabelPanel = new javax.swing.JPanel();
        buscarEspaciosDisponiblesLabel = new javax.swing.JLabel();
        almacenButtonsPanel = new javax.swing.JPanel();
        buscarPCsButton = new javax.swing.JButton();
        buscarComponentesButton = new javax.swing.JButton();
        tecnicoTallerPanel = new javax.swing.JPanel();
        tallerButtonsPanel = new javax.swing.JPanel();
        registrarMontajePCButton = new javax.swing.JButton();
        gerenteVentasPanel = new javax.swing.JPanel();
        ventasButtonsPanel = new javax.swing.JPanel();
        pedirComponentesButton = new javax.swing.JButton();
        procesarPedidoPCButton = new javax.swing.JButton();
        registrarOrdenMontajeButton = new javax.swing.JButton();
        registrarPedidoClienteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ModelPC - Iniciar sesión");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0), "ModelPC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 36)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 0, 0)))); // NOI18N
        panelInicio.setMaximumSize(new java.awt.Dimension(250, 250));
        panelInicio.setMinimumSize(new java.awt.Dimension(250, 250));
        panelInicio.setPreferredSize(new java.awt.Dimension(300, 300));
        panelInicio.setLayout(new java.awt.GridLayout(3, 1, 0, 8));

        DNITextField.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        DNITextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 6)), "DNI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 18))); // NOI18N
        DNITextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNITextFieldActionPerformed(evt);
            }
        });
        panelInicio.add(DNITextField);

        passwordField.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        passwordField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 6)), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 18))); // NOI18N
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        panelInicio.add(passwordField);

        loginButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        loginButton.setText("Iniciar sesión");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        panelInicio.add(loginButton);

        getContentPane().add(panelInicio, "card2");

        personalAlmacenPanel.setBackground(new java.awt.Color(255, 255, 255));
        personalAlmacenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal de almacen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 18))); // NOI18N
        personalAlmacenPanel.setLayout(new java.awt.BorderLayout());

        almacenLabelPanel.setBackground(new java.awt.Color(255, 255, 255));
        almacenLabelPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(48, 32, 0, 32));
        almacenLabelPanel.setLayout(new javax.swing.BoxLayout(almacenLabelPanel, javax.swing.BoxLayout.LINE_AXIS));

        buscarEspaciosDisponiblesLabel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        buscarEspaciosDisponiblesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarEspaciosDisponiblesLabel.setText("Buscar espacios disponibles:");
        almacenLabelPanel.add(buscarEspaciosDisponiblesLabel);

        personalAlmacenPanel.add(almacenLabelPanel, java.awt.BorderLayout.PAGE_START);

        almacenButtonsPanel.setBackground(new java.awt.Color(255, 255, 255));
        almacenButtonsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 32, 32));
        almacenButtonsPanel.setLayout(new java.awt.GridLayout(1, 2, 32, 0));

        buscarPCsButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buscarPCsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uva/eii/ds/empresa15/assets/desktop.png"))); // NOI18N
        buscarPCsButton.setText("PCs");
        buscarPCsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarPCsButton.setIconTextGap(8);
        buscarPCsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarPCsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPCsButtonActionPerformed(evt);
            }
        });
        almacenButtonsPanel.add(buscarPCsButton);

        buscarComponentesButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buscarComponentesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uva/eii/ds/empresa15/assets/motherboard.png"))); // NOI18N
        buscarComponentesButton.setText("Componentes");
        buscarComponentesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarComponentesButton.setIconTextGap(8);
        buscarComponentesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarComponentesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarComponentesButtonActionPerformed(evt);
            }
        });
        almacenButtonsPanel.add(buscarComponentesButton);

        personalAlmacenPanel.add(almacenButtonsPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(personalAlmacenPanel, "personalAlmacenCard");

        tecnicoTallerPanel.setBackground(new java.awt.Color(255, 255, 255));
        tecnicoTallerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Técnico de taller", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 18))); // NOI18N
        tecnicoTallerPanel.setLayout(new java.awt.GridLayout(1, 0));

        tallerButtonsPanel.setBackground(new java.awt.Color(255, 255, 255));
        tallerButtonsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 32, 32));
        tallerButtonsPanel.setLayout(new java.awt.GridLayout(1, 2, 32, 0));

        registrarMontajePCButton.setText("Registrar montaje PC");
        registrarMontajePCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMontajePCButtonActionPerformed(evt);
            }
        });
        tallerButtonsPanel.add(registrarMontajePCButton);

        tecnicoTallerPanel.add(tallerButtonsPanel);

        getContentPane().add(tecnicoTallerPanel, "tecnicoTallerCard");

        gerenteVentasPanel.setBackground(new java.awt.Color(255, 255, 255));
        gerenteVentasPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerente de ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 18))); // NOI18N
        gerenteVentasPanel.setLayout(new java.awt.GridLayout(1, 0));

        ventasButtonsPanel.setBackground(new java.awt.Color(255, 255, 255));
        ventasButtonsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 32, 32));
        ventasButtonsPanel.setLayout(new java.awt.GridLayout(1, 2, 32, 0));

        pedirComponentesButton.setText("Pedir componentes");
        ventasButtonsPanel.add(pedirComponentesButton);

        procesarPedidoPCButton.setText("Procesar pedido PC");
        procesarPedidoPCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarPedidoPCButtonActionPerformed(evt);
            }
        });
        ventasButtonsPanel.add(procesarPedidoPCButton);

        registrarOrdenMontajeButton.setText("Registrar orden de montaje");
        ventasButtonsPanel.add(registrarOrdenMontajeButton);

        registrarPedidoClienteButton.setText("Registrar pedido de cliente");
        registrarPedidoClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPedidoClienteButtonActionPerformed(evt);
            }
        });
        ventasButtonsPanel.add(registrarPedidoClienteButton);

        gerenteVentasPanel.add(ventasButtonsPanel);

        getContentPane().add(gerenteVentasPanel, "gerenteVentasCard");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        processLogin();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        processLogin();
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void buscarPCsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPCsButtonActionPerformed

    }//GEN-LAST:event_buscarPCsButtonActionPerformed

    private void buscarComponentesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarComponentesButtonActionPerformed

    }//GEN-LAST:event_buscarComponentesButtonActionPerformed

    private void procesarPedidoPCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarPedidoPCButtonActionPerformed

    }//GEN-LAST:event_procesarPedidoPCButtonActionPerformed

    private void registrarMontajePCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMontajePCButtonActionPerformed

    }//GEN-LAST:event_registrarMontajePCButtonActionPerformed

    private void registrarPedidoClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPedidoClienteButtonActionPerformed
      this.controlador.showRegistrarPedidoCliente();
    }//GEN-LAST:event_registrarPedidoClienteButtonActionPerformed

    private void DNITextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNITextFieldActionPerformed

    }//GEN-LAST:event_DNITextFieldActionPerformed

    private void processLogin() {
        String dni = DNITextField.getText();
        char[] password = passwordField.getPassword();
        controlador.procesaEventoIdentificarse(dni, password);
    }
    
    /**
     * Muestra un mensaje de error
     * @param mensajeError mensaje de error
     */
    public void mostrarMensajeError(String mensajeError) {
        JOptionPane.showMessageDialog(this, mensajeError,
                "Error de identificacion: credenciales incorrectos", JOptionPane.ERROR_MESSAGE);
        passwordField.setText("");
    }
    
    /**
     * Muestra las opciones de rol en funcion del rol del empleado
     * @param e empleado
     */
    public void mostrarOpcionesRol(Empleado e) {
        Rol rol = e.getRolEnLaEmpresa();
        if (rol instanceof PersonalAlmacen) {
            mostrarOpcionesPersonalAlmacen();
        } else if (rol instanceof GerenteDeVentas) {
            mostrarOpcionesGerenteVentas();
        } else if (rol instanceof TecnicoDelTaller) {
            mostrarOpcionesTecnicoTaller();
        }
    }
    
    /**
     * Muestra las opciones del gerente de ventas
     */
    public void mostrarOpcionesGerenteVentas() {
        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "gerenteVentasCard");
    }
    
    /**
     * Muestra las opciones del personal de almacen
     */
    public void mostrarOpcionesPersonalAlmacen() {
        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "personalAlmacenCard");
    }
    
    /**
     * Muestra las opciones de tecnico de taller
     */
    public void mostrarOpcionesTecnicoTaller() {
        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "tecnicoTallerCard");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNITextField;
    private javax.swing.JPanel almacenButtonsPanel;
    private javax.swing.JPanel almacenLabelPanel;
    private javax.swing.JButton buscarComponentesButton;
    private javax.swing.JLabel buscarEspaciosDisponiblesLabel;
    private javax.swing.JButton buscarPCsButton;
    private javax.swing.JPanel gerenteVentasPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton pedirComponentesButton;
    private javax.swing.JPanel personalAlmacenPanel;
    private javax.swing.JButton procesarPedidoPCButton;
    private javax.swing.JButton registrarMontajePCButton;
    private javax.swing.JButton registrarOrdenMontajeButton;
    private javax.swing.JButton registrarPedidoClienteButton;
    private javax.swing.JPanel tallerButtonsPanel;
    private javax.swing.JPanel tecnicoTallerPanel;
    private javax.swing.JPanel ventasButtonsPanel;
    // End of variables declaration//GEN-END:variables
}
